### ISSUE TITLE
Sorting by date on the report doesn't work

### ISSUE THREAD

**Issue by furicle** [bwya77/PSHTML-AD-Report#11]
If you click on a heading of a date field, it is sorting as a string, not as a date.

So the results look like this....

![2018-12-05_12-20-49](https://user-images.githubusercontent.com/45774/49531465-562f9600-f888-11e8-9117-3da2acd073d9.png)

**Comment by bwya77** [comment]
Thanks I am looking into this

**Comment by bwya77** [comment]
Just tried it on my end, it first ordered it from oldest to newest, clicking again modified it from newest to oldest. I did not change anything but I am working with v1.0.3

**Comment by Tor9299** [comment]
Version 1.0.3 is still not allowing dates to sort correctly.

Interestingly, the only date field that is sorting correctly for me is the "When Changed" field on the AD Objects last modified in last 7 days on the Dashboard tab. Every other date that I've tried in the report will not sort correctly.

To test, show All entries, then sort by the date heading. This is reproducible for Last Logon, Password Last Set, Modified Date, and creation date.
