### ISSUE TITLE
Feature Request: Detailed OS Pie Graph

### ISSUE THREAD

**Issue by bwya77** [bwya77/PSHTML-AD-Report#12]
any chance we can get windows 2019 Versions and identify Windows 10 Pro/Enterprise and LTSC in the pie charts. it would also be helpful on the pie charts to put the number of devices rather than hover over them.

other then that looks great. Wishlist: export to word format for a document to deliver management.

- dsobrero

**Comment by furicle** [comment]
An 'Other' bucket would be nice to - for OSX, Linux, BSD etc...

**Comment by ellisdee9** [comment]
Where might the updated version be?
