### ISSUE TITLE
Save-HTMLReport error

### ISSUE THREAD

**Issue by entwinedgerm** [bwya77/PSHTML-AD-Report#21]
Save-HTMLReport : Cannot bind argument to parameter 'ReportContent' because it is null.
At line:1 char:32
+ Save-HTMLReport -ReportContent $FinalReport -ShowReport -ReportName $ ...
+                                ~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Save-HTMLReport], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Save-HTMLReport

Get-HTMLContentDataTable : Cannot bind argument to parameter 'ArrayOfObjects' because it is an empty collection.
At line:1 char:45
+ ... eport.Add($(Get-HTMLContentDataTable $PasswordExpireSoonTable -HideFo ...
+                                          ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-HTMLContentDataTable], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyCollectionNotAllowed,Get-HTMLContentDataTable

**Comment by viorelfoamete** [comment]
I have exactly the same problem here, with $PasswordExpireSoonTable and $FinalReport whom I guess is caused by the first

**Comment by entwinedgerm** [comment]
I should mention it's running PS5 and Server 2016

**Comment by entwinedgerm** [comment]
It corrected the issue on my end. Thanks

**Comment by bwya77** [comment]
Merged to master branch
