### ISSUE TITLE
Feature Request: Identify Non-Windows OSes

### ISSUE THREAD

**Issue by ecrist** [bwya77/PSHTML-AD-Report#22]
The report currently does a decent job of reporting on the joined Windows systems and displaying the breakdown by OS version.  It does completely lack identification of non-Windows in the "Computer Overview" section.  It does identify those in the "Computers" section.  This data is also lacking in the "Computers Operating System Breakdown" section.  For the latter, I'd suggest two charts, the one you already have, and another for a breakdown of Windows vs Non-Windows categories.

In our organization we have 902 joined systems.  412 CentOS, 408 Windows, 14 Darwin, 14 Hyper-V Server, 1 Solaris, and 53 blank/unknown entries.

![screen shot 2018-12-06 at 8 11 10 am](https://user-images.githubusercontent.com/1800255/49589667-9433c500-f92f-11e8-93bc-0384323408ee.png)

**Comment by bwya77** [comment]
Now leverages Regex to get OS names and places them in the pie graph and top table.

**Comment by ecrist** [comment]
The latest release of this script still doesn't capture non-Windows hosts.
