### ISSUE TITLE
Illegal character during run

### ISSUE THREAD

**Issue by bwya77** [bwya77/PSHTML-AD-Report#3]
n line 83 had to manually change the "-" character as it was coming up as illegal. Not sure if this was an issue with VScode, GitHub corrupting the code, or some other odd issue. 

		"Pre–Windows 2000 Compatible Access"

**Comment by PrzemyslawKlys** [comment]
It's because of copy/paste from web most likely. While things may look the same they are often something else. There is even extension called Unicode Substitutions that can help you with things, but probably not when it's inside quotes.

**Comment by bwya77** [comment]
Fixed and published
